### ISSUE TITLE
Negative int values in Rdata object

### ISSUE THREAD

**Issue by bambooforest** [phoible/dev#115] opened 2015-07-15 16:08 UTC
does this perhaps have to do with what you mentioned in #108 @drammock ?

**Comment by drammock** [comment] 2015-07-15 18:25
Closing as duplicate of #109.  The negative inventory IDs are for inventories that could not be unambiguously identified in the mapping table, based on ISO + Source + Bibkey.  See comments in the aggregation script (lines 83-127, esp. line 111).

**Closed by drammock** 2015-07-15 18:25 UTC
